# Generated by Django 5.2.6 on 2025-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account ID for OAuth authentication', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_oauth_user',
            field=models.BooleanField(default=False, help_text='True if user registered via OAuth (Google)'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="URL to user's profile picture from Google", null=True),
        ),
    ]
