# Generated by Django 5.2.6 on 2025-10-01 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('llama', 'LLaMA'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('other', 'Other')], help_text='AI model name', max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for this model (encrypted in production)', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is currently active')),
                ('max_tokens', models.IntegerField(default=2000, help_text='Maximum tokens per request')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature setting for response generation')),
                ('supports_english', models.BooleanField(default=True, help_text='Whether this model supports English')),
                ('supports_arabic', models.BooleanField(default=True, help_text='Whether this model supports Arabic')),
                ('priority', models.IntegerField(default=0, help_text='Priority order (higher = preferred)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Chat title (auto-generated from first message)', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text='Language used in this chat session', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this chat is archived')),
                ('user', models.ForeignKey(help_text='User who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent this message (user/assistant/system)', max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('ai_model', models.CharField(blank=True, choices=[('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('llama', 'LLaMA'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('other', 'Other')], help_text='AI model used to generate this response (if assistant)', max_length=20, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], help_text='Language of this message', max_length=2)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used for this message (if AI response)')),
                ('response_time', models.FloatField(default=0.0, help_text='Time taken to generate response in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(help_text='Chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], help_text='Language of the summary', max_length=2)),
                ('summary_text', models.TextField(help_text="AI-generated summary of user's interests and conversation patterns")),
                ('topics', models.JSONField(default=list, help_text='List of main topics discussed by the user')),
                ('preferences', models.JSONField(default=dict, help_text='User preferences extracted from conversations')),
                ('chat_count', models.IntegerField(default=0, help_text='Number of chats analyzed for this summary')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages analyzed for this summary')),
                ('ai_model_used', models.CharField(choices=[('grok', 'Grok'), ('deepseek', 'DeepSeek'), ('llama', 'LLaMA'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('other', 'Other')], help_text='AI model used to generate this summary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User summaries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_cha_user_id_6c571d_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'language'], name='chatbot_cha_user_id_2dbf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chatbot_mes_chat_id_cd3a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='chatbot_mes_role_028558_idx'),
        ),
        migrations.AddIndex(
            model_name='usersummary',
            index=models.Index(fields=['user', 'language'], name='chatbot_use_user_id_632437_idx'),
        ),
        migrations.AddIndex(
            model_name='usersummary',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_use_user_id_85c59e_idx'),
        ),
    ]
