# Generated by Django 5.2.6 on 2025-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='name',
            field=models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model used to generate this response (if assistant)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersummary',
            name='ai_model_used',
            field=models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model used to generate this summary', max_length=20),
        ),
    ]
