# Generated by Django 5.2.6 on 2025-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_groq_anthropic_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='name',
            field=models.CharField(choices=[('groq', 'Groq'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('groq', 'Groq'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model used to generate this response (if assistant)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersummary',
            name='ai_model_used',
            field=models.CharField(choices=[('groq', 'Groq'), ('anthropic', 'Anthropic'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model used to generate this summary', max_length=20),
        ),
    ]
