# Generated by Django 5.2.6 on 2025-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_aimodelconfig_name_alter_message_ai_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='name',
            field=models.CharField(choices=[('groq', 'Groq'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('groq', 'Groq'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model used to generate this response (if assistant)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersummary',
            name='ai_model_used',
            field=models.CharField(choices=[('groq', 'Groq'), ('llama', 'LLaMA'), ('other', 'Other')], help_text='AI model used to generate this summary', max_length=20),
        ),
    ]
