# Generated by Django 5.2.6 on 2025-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_aimodelconfig_name_alter_message_ai_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='preferences',
            field=models.JSONField(default=list, help_text='User preferences extracted from conversations'),
        ),
    ]
