# Generated by Django 5.2.6 on 2025-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_usersummary_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersummary',
            name='preferences',
        ),
        migrations.AddField(
            model_name='usersummary',
            name='common_queries',
            field=models.JSONField(default=list, help_text='User queries extracted from conversations'),
        ),
    ]
